### ISSUE TITLE
Authentication: config enhancements

### ISSUE THREAD

**Issue by chucker** [trenz-gmbh/trenz-docs-api#12]
If `appsettings.local.json` does not contain an `Authentication` section, `.authz` files are ignored. (Maybe log a warning?)

If it _does_ exist, what does it look like?

* do we support multiple providers? If so, how do they overlap in terms of claims resolution?
* do we need anything other than an endpoint?

```json
  "Authentication": [
    {
      "Name": "my-authn-api",
      "Url": "https://api.company.example/signin"
    }
  ]
```

**Comment by ricardoboss** [comment]
How would different providers overlap?

The user must choose an auth provider they want to authenticate with (i.e. "Sign in with Google" or "Sign in with Facebook") and if their credentials don't work, no token is issued.  
Otherwise the chosen auth provider returns a token containing: who is the user (UID), which groups do they belong to (GIDs), who authenticated the user (ISS)

**Comment by chucker** [comment]
>How would different providers overlap?

I'm not sure this can be resolved in a useful manner. We _could_ do what we've discussed with claim[^1] suffixes. For example:

* in `.authz`, you write a claim as `accounting`, `developers`, etc.
* in `appsettings.local.json`, you write `claim-suffix: @company.example`

As a result, the actual claim becomes `accounting@company.example`. If any of the auth providers offers this claim, there you go.

[^1]: By "claim", I technically mean an `Sid` claim here, i.e. a group.

>The user must choose an auth provider they want to authenticate with (i.e. "Sign in with Google" or "Sign in with Facebook") and if their credentials don't work, no token is issued.

It doesn't really matter if the credentials "work"; it only matters if

1. the config allows the auth provider and
2. the claim mentioned in the `.authz` is also among those issued by the auth provider

But we don't really have to support multiple providers.

**Comment by ricardoboss** [comment]
Shouldn't auth providers issue different claims in any case?

So if `ap1` grants me `user@ap1.com` and `admin@ap1.com`  
and `ap2` grants me `user@ap2.com` and `editor@ap2.com`
your point is: what happens when the `.authz` contains `user`?

**Comment by chucker** [comment]
I think this problem is too hypothetical. Maybe just allow one auth provider for now.

**Comment by ricardoboss** [comment]
Something like this:

```json
  "Auth": {
    "Type": "TRENZ.Docs.API.Services.Auth.JwtCookieAuthAdapter",
    "Endpoint": "http://localhost:5168/signin",
    "Secret": "$up3r!$zcr3t."
  }
```
