### ISSUE TITLE
Hyphen URLs aren't quite right

### ISSUE THREAD

**Issue by chucker** [trenz-gmbh/trenz-docs-api#18]
If a physical file `docs/public/MyTopic/Some-Title.md` exists and is linked with `(MyTopic/Some-Title.md)`, the API currently does not find it. Instead, it expects to find the document at `MyTopic/Some%20Title.md`.

**Comment by ricardoboss** [comment]
I think this Problem is more general: all links may need to be rewritten, either by the frontend or before indexing. Images and relative links need to be adjusted somehow.
